[theme]
# Primary accent color for interactive elements
primaryColor="#ffffff"

# Background color for the main content area
backgroundColor="#17324a"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor="#586e75"

# Color used for almost all text.
textColor="#fff"